version: '3'

services:

#  Config servers :
  vdm-database-configServer1:
    container_name: vdm-database-configServer1
    image: mongo
    command: mongod --configsvr --replSet configServers --port 27017 --dbpath /data/db
#    ports:
#      - 40001:27017
    volumes:
      - configServer1:/data/db
      - ./config/config-server:/docker-entrypoint-initdb.d/
    networks:
      - docker-vdm_vdm-network
    depends_on:
      - vdm-database-configServer2
      - vdm-database-configServer3

  vdm-database-configServer2:
    container_name: vdm-database-configServer2
    image: mongo
    command: mongod --configsvr --replSet configServers --port 27017 --dbpath /data/db
#    ports:
#      - 40002:27017
    volumes:
      - configServer2:/data/db
    networks:
      - docker-vdm_vdm-network

  vdm-database-configServer3:
    container_name: vdm-database-configServer3
    image: mongo
    command: mongod --configsvr --replSet configServers --port 27017 --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - configServer3:/data/db
    networks:
      - docker-vdm_vdm-network

#  Shards :
  #  Shard 1 :
  vdm-database-shard1server1:
    container_name: vdm-database-shard1server1
    image: mongo
    command: mongod --shardsvr --replSet shard1servers --port 27017 --dbpath /data/db
#    ports:
#      - 50001:27017
    volumes:
      - shard1server1:/data/db
      - ./config/shard-1:/docker-entrypoint-initdb.d/
    depends_on:
      - vdm-database-shard1server2
      - vdm-database-shard1server3
    networks:
      - docker-vdm_vdm-network

  vdm-database-shard1server2:
    container_name: vdm-database-shard1server2
    image: mongo
    command: mongod --shardsvr --replSet shard1servers --port 27017 --dbpath /data/db
#    ports:
#      - 50002:27017
    volumes:
      - shard1server2:/data/db
    networks:
      - docker-vdm_vdm-network

  vdm-database-shard1server3:
    container_name: vdm-database-shard1server3
    image: mongo
    command: mongod --shardsvr --replSet shard1servers --port 27017 --dbpath /data/db
#    ports:
#      - 50003:27017
    volumes:
      - shard1server3:/data/db
    networks:
      - docker-vdm_vdm-network

  #  Shard 2 :
  vdm-database-shard2server1:
    container_name: vdm-database-shard2server1
    image: mongo
    command: mongod --shardsvr --replSet shard2servers --port 27017 --dbpath /data/db
#    ports:
#      - 50101:27017
    volumes:
      - shard2server1:/data/db
      - ./config/shard-2:/docker-entrypoint-initdb.d/
    networks:
      - docker-vdm_vdm-network
    depends_on:
      - vdm-database-shard2server2
      - vdm-database-shard2server3

  vdm-database-shard2server2:
    container_name: vdm-database-shard2server2
    image: mongo
    command: mongod --shardsvr --replSet shard2servers --port 27017 --dbpath /data/db
#    ports:
#      - 50102:27017
    volumes:
      - shard2server2:/data/db
    networks:
      - docker-vdm_vdm-network

  vdm-database-shard2server3:
    container_name: vdm-database-shard2server3
    image: mongo
    command: mongod --shardsvr --replSet shard2servers --port 27017 --dbpath /data/db
#    ports:
#      - 50103:27017
    volumes:
      - shard2server3:/data/db
    networks:
      - docker-vdm_vdm-network

  #  Shard 3 :
  vdm-database-shard3server1:
    container_name: vdm-database-shard3server1
    image: mongo
    command: mongod --shardsvr --replSet shard3servers --port 27017 --dbpath /data/db
#    ports:
#      - 50201:27017
    volumes:
      - shard3server1:/data/db
      - ./config/shard-3:/docker-entrypoint-initdb.d/
    networks:
      - docker-vdm_vdm-network
    depends_on:
      - vdm-database-shard3server2
      - vdm-database-shard3server3

  vdm-database-shard3server2:
    container_name: vdm-database-shard3server2
    image: mongo
    command: mongod --shardsvr --replSet shard3servers --port 27017 --dbpath /data/db
#    ports:
#      - 50202:27017
    volumes:
      - shard3server2:/data/db
    networks:
      - docker-vdm_vdm-network

  vdm-database-shard3server3:
    container_name: vdm-database-shard3server3
    image: mongo
    command: mongod --shardsvr --replSet shard3servers --port 27017 --dbpath /data/db
#    ports:
#      - 50203:27017
    volumes:
      - shard3server3:/data/db
    networks:
      - docker-vdm_vdm-network

#  Mongos :
  vdm-database-mongos:
    container_name: vdm-database-mongos
    image: mongo
    command: sh -c "sleep 30 && mongos --configdb configServers/vdm-database-configServer1:27017,vdm-database-configServer2:27017,vdm-database-configServer3:27017 --bind_ip 0.0.0.0 --port 27017"
    ports:
      - 27017:27017
    volumes:
      - ./config/mongos:/docker-entrypoint-initdb.d/
    networks:
      - docker-vdm_vdm-network
    depends_on:
      - vdm-database-configServer1
      - vdm-database-configServer2
      - vdm-database-configServer3
      - vdm-database-shard1server1
      - vdm-database-shard1server2
      - vdm-database-shard1server3
      - vdm-database-shard2server1
      - vdm-database-shard2server2
      - vdm-database-shard2server3
      - vdm-database-shard3server1
      - vdm-database-shard3server2
      - vdm-database-shard3server3

volumes:
  configServer1:
    driver: local
  configServer2:
    driver: local
  configServer3:
    driver: local
  shard1server1:
    driver: local
  shard1server2:
    driver: local
  shard1server3:
    driver: local
  shard2server1:
    driver: local
  shard2server2:
    driver: local
  shard2server3:
    driver: local
  shard3server1:
    driver: local
  shard3server2:
    driver: local
  shard3server3:
    driver: local

networks:
  docker-vdm_vdm-network:
      external: true