version: "3"

services:
  vdm-api:
    container_name: vdm-api
    build: ../api
    image: vdm-api
    command: npm start
    ports:
      - 8000:8000
    depends_on:
      - vdm-database-mongos
    networks:
      - vdm-network
    deploy:
      replicas: 2

  vdm-front:
    container_name: vdm-front
    build: ../front
    image: vdm-front
    command: npm run serve
    ports:
      - 8080:3000
    networks:
      - vdm-network
    deploy:
      replicas: 2

  vdm-proxy:
    container_name: vdm-proxy
    image: vdm-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - vdm-network
    depends_on:
      - vdm-api
      - vdm-front

  # Database --v-- :
  #  Config servers :
  vdm-database-configServer1:
    container_name: vdm-database-configServer1
    build: ./database
    image: vdm-database
    command: mongod --configsvr --replSet configServers --port 27017 --dbpath /data/db
    #    ports:
    #      - 40001:27017
    volumes:
      - configServer1:/data/db
#      - ./database/config/config-server:/docker-entrypoint-initdb.d/
#      - ./database/backups/configServer1:/backup
    networks:
      - vdm-network
    depends_on:
      - vdm-database-configServer2
      - vdm-database-configServer3

  vdm-database-configServer2:
    container_name: vdm-database-configServer2
    build: ./database
    image: vdm-database
    command: mongod --configsvr --replSet configServers --port 27017 --dbpath /data/db
    #    ports:
    #      - 40002:27017
    volumes:
      - configServer2:/data/db
#      - ./database/backups/configServer2:/backup
    networks:
      - vdm-network

  vdm-database-configServer3:
    container_name: vdm-database-configServer3
    build: ./database
    image: vdm-database
    command: mongod --configsvr --replSet configServers --port 27017 --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - configServer3:/data/db
#      - ./database/backups/configServer3:/backup
    networks:
      - vdm-network

  #  Shards :
  #  Shard 1 :
  vdm-database-shard1server1:
    container_name: vdm-database-shard1server1
    build: ./database
    image: vdm-database
    privileged: true
    command: mongod --shardsvr --replSet shard1servers --port 27017 --dbpath /data/db
    #    ports:
    #      - 50001:27017
    volumes:
      - shard1server1:/data/db
#      - ./database/config/shard-1:/docker-entrypoint-initdb.d/
#      - ./database/backups/shard1server1:/backup
    networks:
      - vdm-network
    depends_on:
      - vdm-database-shard1server2
      - vdm-database-shard1server3

  vdm-database-shard1server2:
    container_name: vdm-database-shard1server2
    build: ./database
    image: vdm-database
    command: mongod --shardsvr --replSet shard1servers --port 27017 --dbpath /data/db
    #    ports:
    #      - 50002:27017
    volumes:
      - shard1server2:/data/db
#      - ./database/backups/shard1server2:/backup
    networks:
      - vdm-network

  vdm-database-shard1server3:
    container_name: vdm-database-shard1server3
    build: ./database
    image: vdm-database
    command: mongod --shardsvr --replSet shard1servers --port 27017 --dbpath /data/db
    #    ports:
    #      - 50003:27017
    volumes:
      - shard1server3:/data/db
#      - ./database/backups/shard1server3:/backup
    networks:
      - vdm-network

  #  Shard 2 :
  vdm-database-shard2server1:
    container_name: vdm-database-shard2server1
    build: ./database
    image: vdm-database
    command: mongod --shardsvr --replSet shard2servers --port 27017 --dbpath /data/db
    #    ports:
    #      - 50101:27017
    volumes:
      - shard2server1:/data/db
#      - ./database/config/shard-2:/docker-entrypoint-initdb.d/
#      - ./database/backups/shard2server1:/backup
    networks:
      - vdm-network
    depends_on:
      - vdm-database-shard2server2
      - vdm-database-shard2server3

  vdm-database-shard2server2:
    container_name: vdm-database-shard2server2
    build: ./database
    image: vdm-database
    command: mongod --shardsvr --replSet shard2servers --port 27017 --dbpath /data/db
    #    ports:
    #      - 50102:27017
    volumes:
      - shard2server2:/data/db
#      - ./database/backups/shard2server2:/backup
    networks:
      - vdm-network

  vdm-database-shard2server3:
    container_name: vdm-database-shard2server3
    build: ./database
    image: vdm-database
    command: mongod --shardsvr --replSet shard2servers --port 27017 --dbpath /data/db
    #    ports:
    #      - 50103:27017
    volumes:
      - shard2server3:/data/db
#      - ./database/backups/shard2server3:/backup
    networks:
      - vdm-network

  #  Shard 3 :
  vdm-database-shard3server1:
    container_name: vdm-database-shard3server1
    build: ./database
    image: vdm-database
    command: mongod --shardsvr --replSet shard3servers --port 27017 --dbpath /data/db
    #    ports:
    #      - 50201:27017
    volumes:
      - shard3server1:/data/db
#      - ./database/config/shard-3:/docker-entrypoint-initdb.d/
#      - ./database/backups/shard3server1:/backup
    networks:
      - vdm-network
    depends_on:
      - vdm-database-shard3server2
      - vdm-database-shard3server3

  vdm-database-shard3server2:
    container_name: vdm-database-shard3server2
    build: ./database
    image: vdm-database
    command: mongod --shardsvr --replSet shard3servers --port 27017 --dbpath /data/db
    #    ports:
    #      - 50202:27017
    volumes:
      - shard3server2:/data/db
#      - ./database/backups/shard3server2:/backup
    networks:
      - vdm-network

  vdm-database-shard3server3:
    container_name: vdm-database-shard3server3
    build: ./database
    image: vdm-database
    command: mongod --shardsvr --replSet shard3servers --port 27017 --dbpath /data/db
    #    ports:
    #      - 50203:27017
    volumes:
      - shard3server3:/data/db
#      - ./database/backups/shard3server3:/backup
    networks:
      - vdm-network

  #  Mongos :
  vdm-database-mongos:
    container_name: vdm-database-mongos
    build: ./database
    image: vdm-database
    command: sh -c "sleep 30 && mongos --configdb configServers/vdm-database-configServer1:27017,vdm-database-configServer2:27017,vdm-database-configServer3:27017 --bind_ip 0.0.0.0 --port 27017"
    ports:
      - 27017:27017
#    volumes:
#      - ./database/config/mongos:/docker-entrypoint-initdb.d/
#      - ./database/backups/mongos:/backup
    networks:
      - vdm-network
    depends_on:
      - vdm-database-configServer1
      - vdm-database-configServer2
      - vdm-database-configServer3
      - vdm-database-shard1server1
      - vdm-database-shard1server2
      - vdm-database-shard1server3
      - vdm-database-shard2server1
      - vdm-database-shard2server2
      - vdm-database-shard2server3
      - vdm-database-shard3server1
      - vdm-database-shard3server2
      - vdm-database-shard3server3


volumes:
  configServer1:
    driver: local
  configServer2:
    driver: local
  configServer3:
    driver: local
  shard1server1:
    driver: local
  shard1server2:
    driver: local
  shard1server3:
    driver: local
  shard2server1:
    driver: local
  shard2server2:
    driver: local
  shard2server3:
    driver: local
  shard3server1:
    driver: local
  shard3server2:
    driver: local
  shard3server3:
    driver: local

networks:
  vdm-network:
    driver: overlay