version: '3'

services:

  vdm-database-shard1server1:
    container_name: vdm-database-shard1server1
    image: mongo
    command: mongod --shardsvr --replSet shard1servers --port 27017 --dbpath /data/db
    ports:
      - 50001:27017
    volumes:
      - shard1server1:/data/db

  vdm-database-shard1server2:
    container_name: vdm-database-shard1server2
    image: mongo
    command: mongod --shardsvr --replSet shard1servers --port 27017 --dbpath /data/db
    ports:
      - 50002:27017
    volumes:
      - shard1server2:/data/db

  vdm-database-shard1server3:
    container_name: vdm-database-shard1server3
    image: mongo
    command: mongod --shardsvr --replSet shard1servers --port 27017 --dbpath /data/db
    ports:
      - 50003:27017
    volumes:
      - shard1server3:/data/db

volumes:
  shard1server1:
    driver: local
  shard1server2:
    driver: local
  shard1server3:
    driver: local
