version: '3'

services:

  vdm-database-configServer1:
    container_name: vdm-database-configServer1
    image: mongo
    command: mongod --configsvr --replSet configServers --port 27017 --dbpath /data/db
    ports:
      - 40001:27017
    volumes:
      - configServer1:/data/db
      - ./config:/docker-entrypoint-initdb.d/
    networks:
      - vdm-database
    depends_on:
      - vdm-database-configServer2
      - vdm-database-configServer3

  vdm-database-configServer2:
    container_name: vdm-database-configServer2
    image: mongo
    command: mongod --configsvr --replSet configServers --port 27017 --dbpath /data/db
    ports:
      - 40002:27017
    volumes:
      - configServer2:/data/db
    networks:
      - vdm-database

  vdm-database-configServer3:
    container_name: vdm-database-configServer3
    image: mongo
    command: mongod --configsvr --replSet configServers --port 27017 --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - configServer3:/data/db
    networks:
      - vdm-database

volumes:
  configServer1:
    driver: local
  configServer2:
    driver: local
  configServer3:
    driver: local

networks:
  vdm-database:
    driver: bridge