sleep 30
mongo --eval 'sh.addShard("shard1servers/vdm_vdm-database-shard1server.1:27017,vdm_vdm-database-shard1server.2:27017,vdm_vdm-database-shard1server.3:27017")'
mongo --eval 'sh.addShard("shard2servers/vdm_vdm-database-shard2server.1:27017,vdm_vdm-database-shard2server.2:27017,vdm_vdm-database-shard2server.3:27017")'
mongo --eval 'sh.addShard("shard3servers/vdm_vdm-database-shard3server.1:27017,vdm_vdm-database-shard3server.2:27017,vdm_vdm-database-shard3server.3:27017")'
mongo --eval 'db.createCollection("vdm.tickets")'
mongo --eval 'db.createCollection("vdm.clients")'
mongo --eval 'db.createCollection("vdm.users")'
mongo --eval 'sh.enableSharding("vdm")'
mongo --eval 'sh.shardCollection("vdm.tickets", { "Acheteur.Email": "hashed" })'
mongo --eval 'sh.shardCollection("vdm.clients", { "Email": "hashed" })'
mongo --eval 'sh.shardCollection("vdm.users", { "Email": "hashed" })'